# playbook.yml
---
- name: Install SP Server
  hosts: linux
  gather_facts: false
  become: false

  vars:
    changed: "false"
    workingdir: "/tmp/baserver"
    # workingdir: "C:/temp/baserver"
    spppassword: "IbmIbm@2025*1357"
    sppnewversion: "8.1.26.000"
    # sppnewversion: "8.1.27.100"
    exclude_patterns:
    - ".git/"
    - "*.tmp"
    - "*.log"
    - "__pycache__/"
    - ".DS_Store"

  tasks:
    - name: Ensure directory exists for sp_baserver
      win_file:
        path: "{{workingdir}}"
        state: directory

    - name: Copy automation framework scripts - sp_baserver.py
      win_copy:
        src: /mnt/c/Users/NikhilTanni/Downloads/Nikk-dev/IBM/ansible-storage-protect/plugins/modules/sp_baserver.py
        dest: "{{workingdir}}/sp_baserver.py"
        when: changed == "true"
    
    - name: Ensure directory exists for sp_baserver_utils
      win_file:
        path: "{{workingdir}}/module_utils"
        state: directory

    - name: Copy automation framework scripts - sp_baserver_utils.py
      win_copy:
        src: /mnt/c/Users/NikhilTanni/Downloads/Nikk-dev/IBM/ansible-storage-protect/plugins/module_utils/sp_server_utils.py
        dest: "{{workingdir}}/module_utils/sp_server_utils.py"
        when: changed == "true"

    - name: Copy automation framework scripts - sp_server_constants.py
      win_copy:
        src: /mnt/c/Users/NikhilTanni/Downloads/Nikk-dev/IBM/ansible-storage-protect/plugins/module_utils/sp_server_constants.py
        dest: "{{workingdir}}/module_utils/sp_server_constants.py"
        when: changed == "true"


    - name: Run the orchestration module
      win_command: "python {{workingdir}}/sp_baserver.py --mode=install --serverpassword=\"{{spppassword}}\" --newversion={{sppnewversion}} --log-level=DEBUG"
      args:
        chdir: "{{workingdir}}"
      register: output

    - debug: msg="{{ output.stdout }}"

    - debug: msg="{{ output.stderr }}"
        
    
